experiment: 'byol_test'
environment: 'MineRLNavigate-v0'
epochs: 500
lr: 0.001
batch_size: 32
img_size: 64
m: 0.996
delay: yes
trajectories: 'CustomTrajectories2'
split: 0.95
byol:
  mlp_hidden_size: 256
  projection_size: 128
