experiment: 'byol_0.1'
environment: 'MineRLNavigate-v0'
epochs: 500
byol:
  lr: 0.001
  batch_size: 32
  mlp_hidden_size: 256
  projection_size: 128
  img_size: 64
  m: 0.996
  delay: True
  trajectories: 'CustomTrajectories2'
