experiment: 'curl_0.2.5'
environment: 'MineRLNavigate-v0'
batch_size: 32
epochs: 60000
learning_rate: 0.001
soft_update: 2
curl:
  embedding_dim: 50
  img_size: 64
  encoder_tau: 0.005
  load: yes
  epoch: '58000.pt'
gauss_step:
  k_std: 0
  k_mean: 10
