
environment: 'MineRLNavigate-v0'
batch_size: 256
num_training_updates: 15000
learning_rate: 0.001

vqvae:
  num_hiddens: 128
  num_residual_hiddens: 32
  num_residual_layers: 2
  embedding_dim: 64
  num_embeddings: 512
  commitment_cost: 0.25
  decay: 0.99
