experiment: 'curl_0.1.1'
environment: 'MineRLNavigate-v0'
batch_size: 32
epochs: 200
learning_rate: 0.001
seq_len: 10
curl:
  embedding_dim: 50
  img_size: 64
  encoder_tau: 0.005
  load: yes
  epoch: '65000.pt'
