experiment: 'test_2'
environment: 'MineRLNavigate-v0'
batch_size: 256
num_training_updates: 25000
learning_rate: 0.001
split: 0.9
vqvae:
  num_hiddens: 128
  num_residual_hiddens: 32
  num_residual_layers: 2
  embedding_dim: 64
  num_embeddings: 512
  commitment_cost: 0.25
  decay: 0.99
pixelcnn:
  epochs: 100
  save: no
  log_interval: 100
  lr: 0.0003
  img_dim: 16
  batch_size: 32
  num_hiddens: 64
  num_layers: 15
  gen_samples: no
pixelsnail:
  epochs: 100
  save: no
  log_interval: 100
  lr: 0.0003
  img_dim: 16
  batch_size: 32
  channel: 256
  n_res_block: 4
  n_res_channel: 256
  n_out_res_block: 0
  n_cond_res_block: 3
  dropout: 0.1
  kernel_size: 5
  n_block: 4
  n_class: 512
  sched: 'cycle'
