experiment: 'curl_exp_2_embeddings_1'
environment: 'MineRLNavigate-v0'
trajectories: ['CustomTrajectories8']
epochs: 300
batch_size: 32
lr: 0.001
split: 0.90
tau: 0.005
soft_update: 2
img_size: 64
delay: yes
curl:
  k_std: 5
  k_mean: 15
  z_dim: 128
test:
  type: 'reward'  # [index, reward, embed]
  shuffle: no
  limit: null
  path_goal_states: './goal_states/CT8_real_biome_curl_kmeans_10'
  # path_weights: './curl_1.0/mineRL/1042bq9w/checkpoints/epoch=499-step=302999.ckpt'
  path_weights: './curl_exp_0/mineRL/10d8jeqr/checkpoints/epoch=299-step=2099.ckpt'
  # path_weights: './curl_exp_2/mineRL/h7yt76lr/checkpoints/epoch=76-step=1643025.ckpt'
