experiment: 'curl_2.0'
environment: 'MineRLNavigate-v0'
epochs: 400
batch_size: 32
lr: 0.001
trajectories: 'CustomTrajectories4'
split: 0.90
tau: 0.005
soft_update: 2
img_size: 64
delay: yes
curl:
  z_dim: 50
