outdir: 'rl.3.0'
env: 'MineRLNavigate-v0'
logging_level: 20

seed: 0
gpu: 0

demo: yes
monitor: yes
load: './results/train_rl.3.0/best/'
eval_n_runs: 6

agent: 'CategoricalDoubleDQN'
arch: 'distributed_dueling'

max_episode_steps: 3000
batch_size: 32
update_interval: 4
frame_skip: 4
gamma: 0.99
clip_delta: yes
num_step_return: 1
lr: 2.5e-4
adam_eps: 1.e-8

batch_accumulator: 'sum'
gray_scale: no
frame_stack: no

final_exploration_frames: 10.e+6
final_epsilon: 0.01
eval_epsilon: 0.001
noisy_net_sigma: null
replay_capacity: 10.e+6
replay_start_size: 3.e+4
prioritized: yes
target_update_interval: 2.e+4

encoder_version: 'curl_0.3.5'
load_epoch: '70000.pt'
embedding_dim: 50
img_size: 64
threshold: 20
path_goal_states: './goal_states_single_1'
