experiment: 'vqvae_CW0_pixels_coords.sweep'
environment: 'MineRLNavigate-v0'
trajectories: ['CustomTrajectories8']
epochs: 25
delay: no
split: 0.90
lr: 0.001
batch_size: 256
img_size: 64
k_std: 5
k_mean: 15
coord_cost: 0.2
vqvae:
  num_hiddens: 64
  num_residual_hiddens: 32
  num_residual_layers: 2
  embedding_dim: 256
  num_embeddings: 10
  commitment_cost: 0.25
  decay: 0.99
test:
  type: 'centroides'  # [index, reward, embed]
  shuffle: no
  limit: null
  # path_weights: './vqvae_0.3/mineRL/1c4o6jgy/checkpoints/epoch=499-step=37999.ckpt'
  # path_weights: './vqvae_1.0/mineRL/32lwarh6/checkpoints/epoch=199-step=21599.ckpt'
  # path_weights: './vqvae_1.1/mineRL/315ksn7x/checkpoints/epoch=203-step=22031.ckpt'
  # path_weights: './vqvae_1.2/mineRL/3qtc0w0y/checkpoints/epoch=131-step=14255.ckpt'
  # path_weights: './vqvae_2.0/mineRL/kbsmulhw/checkpoints/epoch=49-step=4499.ckpt'
  # path_weights: './vqvae_sweep_1/mineRL/96qj9btc/checkpoints/epoch=44-step=4859.ckpt'
  # path_weights: 'vqvae_3.1/mineRL/8ykl37mx/checkpoints/epoch=59-step=5399.ckpt'
  # path_weights: 'vqvae_sweep_0/mineRL/8bbcrmgb/checkpoints/epoch=34-step=3149.ckpt'
  # path_weights: 'vqvae_exp_0/mineRL/2n13fn6b/checkpoints/epoch=499-step=499.ckpt'
  # path_weights: 'vqvae_exp_1/mineRL/mlq3n3be/checkpoints/epoch=39-step=11679.ckpt'
  # path_weights: 'vqvae_CW_Simple_2/mineRL/l4ctccfy/checkpoints/epoch=39-step=4999.ckpt'
  # path_weights: 'vqvae_CW0_realistic_coord.4/mineRL/3kyxgwil/checkpoints/epoch=39-step=4999.ckpt'
  # path_weights: 'vqvae_CW0_realistic_pixels.0/mineRL/nqxebkf7/checkpoints/epoch=39-step=4999.ckpt'
  # path_weights: 'vqvae_CW0-4_realistic_pixels.0/mineRL/1bvif2wt/checkpoints/epoch=13-step=6839.ckpt'
  # path_weights: 'vqvae_Expert_trajectories_kmeans.0/mineRL/awmhuqtd/checkpoints/epoch=13-step=3933.ckpt'
  # path_weights: 'vqvae_CW0_pixels_coords.0/mineRL/2ygk0z70/checkpoints/epoch=33-step=4155.ckpt'
  # path_weights: 'vqvae_CW0_pixels_coords.1/mineRL/2ebqf4sb/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW0_pixels_coords.2/mineRL/n5eht19c/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW0_pixels_coords.3/mineRL/1h64vg8e/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW0_pixels_coords.4/mineRL/38orh2cb/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW4_coords.0/mineRL/2w75hv6i/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW4_pixels_coords.0/mineRL/uu2pzg5q/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW4_pixels_coords.0/mineRL/8qx1sawb/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW4_pixels_coords.0/mineRL/03o5wr2k/checkpoints/epoch=32-step=4124.ckpt'
  # path_weights: 'vqvae_CW4_pixels_coords.0/mineRL/dhide5as/checkpoints/epoch=32-step=4124.ckpt'
  path_weights: 'vqvae_CW4_pixels_coords.0/mineRL/nozzp87n/checkpoints/epoch=32-step=4124.ckpt'
