experiment: 'vqvae_1.0'
environment: 'MineRLNavigate-v0'
epochs: 200
delay: no
trajectories: 'CustomTrajectories4'
split: 0.90
lr: 0.001
batch_size: 256
img_size: 64
vqvae:
  num_hiddens: 64
  num_residual_hiddens: 32
  num_residual_layers: 2
  embedding_dim: 256
  num_embeddings: 10
  commitment_cost: 0.25
  decay: 0.99
