num: 'Simple'
x: 0
y: 4
z: 0
barrier: 50

#
# Diamond Block location. y coordinate will be overwrited by surface's y
#
dx: -100
dy: 0
dz: 100

# """
# Direction types:
#   'random': 360 possible directions
#   'single': 1 possible direction
#   'cardinal': north/south/west/east
# """

direction: 'random'  # random/single/discrete

# """
# random_position: False -> starts at (x,z)
# random_position: True -> starts at random position in range: (x-range, z-range) to (x+range, z+range)
# """

random_position: True
range: 45
